# Generated by Django 5.1.3 on 2024-11-27 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouOweMe', '0002_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadbeat',
            name='debt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='YouOweMe.debt'),
            preserve_default=False,
        ),
    ]
